version: '3.6'

services:
  mkdocs:
    build: .
    container_name: linux-20
    restart: unless-stopped
    ports:
      - "127.0.6.2:80:80"
    volumes:
      - ./:/mkdocs:ro
networks:
  default:
    external:
      name: compose-default