version: '3.6'

services:
  mkdocs:
    image: "squidfunk/mkdocs-material"
    container_name: linux-20
    restart: unless-stopped
    ports:
      - "127.0.6.2:80:8000"
    volumes:
      - ./:/docs:ro
