# Project information
site_name: 'Debian/Ubuntu Book《Linux 二零》'
site_description: 'Linux 入门书籍，适用于「Debian/Ubuntu 相关发行版」'
site_url: 'https://itboon.github.io/linux-20/'

theme:
  name: 'material'
  language: 'zh'

markdown_extensions:
  - 'codehilite'
  - 'admonition'

dev_addr: '127.0.0.1:7001'

# Repository
repo_name: 'itboon/linux-20'
repo_url: 'https://github.com/itboon/linux-20'
edit_uri: ''

google_analytics:
  - 'UA-159908880-1'
  - 'auto'

# Page tree
nav:
  - '关于本书': 'index.md'
  - 'Linux 基础组件': 'linux/linux.md'
  - '终端和 shell': 'linux/tty-shell.md'
  - '选择 shell': 'linux/choose-shell.md'
  - 'bash shell':
      - '基础命令简介' : 'bash/basic-commands.md'
      - '环境变量' : 'bash/shell-env.md'
      - 'shell 语法' : 'bash/shell-syntax.md'
      - 'shell 字符扩展' : 'bash/shell-expansions.md'
      - '管道和重定向' : 'bash/shell-redirect.md'
      - 'shell 条件语句' : 'bash/shell-conditional.md'
      - 'shell 循环语句' : 'bash/shell-loop.md'
      - '执行文件' : 'bash/exec-file.md'
  - '文件权限':
      - '文件权限基础' : 'file-permission/basic.md'
      - 'chmod 修改文件权限' : 'file-permission/chmod.md'
      - 'chown 修改文件归属' : 'file-permission/chown.md'
      - 'Linux 目录结构简介' : 'file-permission/linux-fhs.md'
  - '管理网络':
      - '配置网络' : 'network/configuration.md'
      - 'iproute2' : 'network/iproute2.md'
  - '管理软件包':
    - '使用 apt 安装软件': 'package-management/apt.md'
    - 'dpkg': 'package-management/dpkg.md'
  - '管理用户和组': 'managing-user/user-and-group.md'
  - 'systemd':
      - 'systemd 和 systemctl' : 'systemd/systemd.md'
      - '基于 systemd 部署服务' : 'systemd/deploying-service.md'
  - '文本处理':
      - 'grep 与正则表达式' : 'text-sculpting/grep-regexp.md'
      - 'sed 流编辑器' : 'text-sculpting/sed.md'
      - 'gawk 基础用法' : 'text-sculpting/awk.md'
  - 'docker':
      - '初试 docker' : 'docker/docker.md'
      - 'docker compose' : 'docker/docker-compose.md'
      - '反向代理和负载均衡' : 'docker/docker-lb.md'