name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: |
        set -ex
        sudo apt-get install -y python3-venv
        python3 -m venv /tmp/mkdocs
        source /tmp/mkdocs/bin/activate
        python --version
        pip --version
        pip install mkdocs mkdocs-material pygments
        mkdocs build
