name: deploy to aliyun oss

on:
  page_build

jobs:
  linux-20_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: copy files to oss
      shell: bash
      env:
        OSS_KEY_ID: ${{ secrets.OSS_KEY_ID }}
        OSS_KEY_SE: ${{ secrets.OSS_KEY_SECRET }}
        OSS_EP: oss-cn-hongkong.aliyuncs.com
        OSS_DL_URL: http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64
        OSS_DEST: oss://linux-20/
      run: |
        mkdir -p ${HOME}/bin
        aliOSS="${HOME}/bin/ossutil"
        curl -o $aliOSS -L $OSS_DL_URL
        chmod a+rx $aliOSS
        $aliOSS config -e $OSS_EP -i $OSS_KEY_ID -k $OSS_KEY_SE
        $aliOSS cp -rf ./ $OSS_DEST
